name: Merge epic/* branch to stg
on:
  push:
    branches:
      - 'epic/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Merge Branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: stg
          github_token: ${{ secrets.GITHUB_TOKEN }}
